# Generated by Django 5.2.10 on 2026-03-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create_complaint', 'Create Complaint'), ('update_status', 'Update Status'), ('create_user', 'Create User'), ('update_user', 'Update User'), ('delete_user', 'Delete User'), ('email_verified', 'Email Verified'), ('verification_sent', 'Verification Email Sent')], max_length=50),
        ),
    ]
