# Generated by Django 5.2.10 on 2026-03-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_feedback',
            field=models.TextField(blank=True, help_text='Feedback for resolved or rejected complaints', null=True),
        ),
    ]
